-- phpMyAdmin SQL Dump
-- version 5.1.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 23, 2021 at 07:22 PM
-- Server version: 10.4.19-MariaDB
-- PHP Version: 7.3.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `article`
--

-- --------------------------------------------------------

--
-- Table structure for table `blogpost`
--

CREATE TABLE `blogpost` (
  `id` int(5) NOT NULL,
  `username` varchar(255) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `recipe` varchar(50) NOT NULL,
  `pre_time` int(4) NOT NULL,
  `cooking_time` int(4) NOT NULL,
  `servings` int(2) NOT NULL,
  `category` varchar(20) NOT NULL,
  `origin` varchar(20) NOT NULL,
  `image` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `description` text NOT NULL,
  `ingredients` text NOT NULL,
  `method` text NOT NULL,
  `likes` int(5) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `blogpost`
--

INSERT INTO `blogpost` (`id`, `username`, `created_at`, `recipe`, `pre_time`, `cooking_time`, `servings`, `category`, `origin`, `image`, `description`, `ingredients`, `method`, `likes`) VALUES
(13, '4nm19cs192', '2021-06-23 11:11:25', 'Indian Dosa', 10, 10, 8, 'Main Course', 'Indian', 'images/articles/1624426885_download (4).jpg', 'Make your own dosa – Indian rice pancakes made from fermented batter. They take a little effort, but are delicious served with aloo masala and other fillings', '50g split urad lentils , washed\r\n1 tbsp channa dal /bengal gram\r\n190g basmati rice\r\n1 tbsp fenugreek seeds (optional)\r\nvegetable oil , for frying', 'STEP 1\r\nWash all the ingredients, except for the oil, three or four times, then drain. Leave to soak in cold water in a bowl overnight. \r\n\r\nSTEP 2\r\nDrain the water from the ingredients, but keep it and set aside. Transfer the soaked ingredients to a food processor and grind to make a smooth paste.  It should be like a thick, smooth pancake batter and should coat the back of a spoon. Empty into a large bowl and cover. Keep it in a warm place overnight to allow the batter to ferment (see tip, below). It will have doubled in quantity and look bubbly. If youre not using the batter straight away, chill for later. It will keep for up to five days.\r\n\r\nSTEP 3\r\nVery gently stir the batter. It will have thickened in consistency, so you can add a little water to give it a thick but pourable consistency.\r\n\r\nSTEP 4\r\nHeat a non-stick frying pan on a low to medium heat for 5 mins. Drizzle over a few drops of oil, then wipe the pan with kitchen paper to get rid of any excess oil. \r\n\r\nSTEP 5\r\nSprinkle a handful of water on the hot pan to cool it, then dry with some kitchen paper. Pour one ladle of the dosa batter in the middle of the pan. Using the bottom of the ladle, quickly move it in a circular motion, allowing the batter to spread outwards from the middle towards the edge of the pan, to form a round, thin pancake.\r\n\r\nSTEP 6\r\nDrizzle a few drops of oil all over the dosa and increase the temperature to a high heat. When it turns slightly golden and the edges begin to lift, add any stuffing (like dosa masala potato stuffing) to the middle. Continue to cook until the underside looks completely golden and crisp. Use a flat spatula to loosen the edges, then roll over the potato stuffing and lift onto a plate. \r\n\r\nSTEP 7\r\nBefore you make the next dosa, decrease the temperature of the pan back to a medium heat and repeat the above steps.', 0),
(14, '4nm19cs192', '2021-06-23 11:17:45', 'Chicken pakoras', 20, 30, 6, 'Appetizer', 'Indian', 'images/articles/Chicken pakoras.jpg', 'Make a batch of these crispy golden pakoras as a snack, or part of an Indian meal. Serve hot with sweet chilli sauce or green chutney.', '700g boneless chicken, cut into bite-sized pieces\r\n2 tbsp cornflour\r\n50g rice flour\r\n40g gram flour, sieved\r\n3 dried chillies, crushed or 3 green chillies, finely chopped\r\n½ tsp chilli powder\r\n½ tsp curry powder\r\n½ tsp ground coriander\r\n½ tsp cumin\r\n2 small onions, chopped\r\nsmall bunch of coriander, finely chopped\r\nvegetable oil, for deep-frying\r\nsweet chilli sauce or green chutney, to serve', 'STEP 1\r\nPut the chicken in a large bowl, then use your hands to coat the pieces in the cornflour. Mix in the rice flour, followed by the gram flour. Add the chillies, spices, onion, coriander and 1 tsp salt. Mix well with your hands.\r\n\r\nSTEP 2\r\nGradually add around 150ml water until the ingredients have become moist and ever-so-slightly wet. You may not need all the water (adding too much will stop the pakora mixture binding).\r\n\r\nSTEP 3\r\nFill a deep pan no more than a third full with vegetable oil and heat to 180C. Squeeze a small amount of the pakora mixture together before carefully lowering into the hot oil with a spoon. Fry for 8-10 mins, turning regularly, until cooked through and browned all over. Set aside on a plate lined with kitchen paper while you repeat with the remaining mixture, frying in small batches. Serve hot with a sweet chilli sauce or green chutney.', 0),
(15, 'rubix', '2021-06-23 12:20:28', 'Japanese-style bento box', 20, 25, 1, 'Main Course', 'Japanese', 'images/articles/Japanese-style bento box.jpg', 'This Asian-inspired lunchbox with mackerel sushi, edamame beans and fresh fruit will keep you going all afternoon', '100g fresh edamame in the pods (or frozen soya beans)\r\nhandful of a favourite fruit , such as fresh pineapple, blueberries or strawberries\r\n\r\nFor the sushi\r\n\r\n100g sushi rice\r\n1 tbsp rice vinegar\r\n½ tsp golden caster sugar\r\n1 sheet nori\r\n1 smoked mackerel fillet, about 75g, flaked\r\n1 tbsp light mayonnaise\r\n2 spring onions , chopped\r\npea-sized blob wasabi (optional)\r\n¼ red pepper , thinly sliced lengthways, about 6 slices', 'STEP 1\r\nBring a pan of water to the boil and cook the edamame for 3-4 mins (or 1-2 mins if using frozen soya beans) until tender. Drain, sprinkle with salt and set aside.\r\n\r\nSTEP 2\r\nRinse the rice well in cold water until the water runs clear. Put the rice in a heavy-based pan with a tight-fitting lid and cover with 200ml water. Bring just to the boil, then put on the lid, turn the heat to its lowest point and cook for 15-20 mins, until the liquid is absorbed. Remove from the heat and leave with the lid on for another 10 mins.\r\n\r\nSTEP 3\r\nSpoon the cooked rice into a wide bowl and leave to cool a little. Stir together the rice vinegar, sugar and a small pinch of salt, until the sugar and salt dissolve. Mix this into the cooled rice. Lay the nori sheet on a sushi rolling mat or sheet of cling film. With damp hands, spread the rice over two-thirds of the nori sheet.\r\n\r\nSTEP 4\r\nMix the smoked mackerel, mayonnaise and spring onions, season well with black pepper. Spread a line of wasabi down the middle of the rice, if using, and layer on the red pepper pieces, then the fish mixture. Roll the sushi up, starting from the end covered with rice. Dampen the uncovered end to help it stick. Slice into about 6 x 3cm thick pieces.\r\n\r\nSTEP 5\r\nPop the sushi rolls into a bento box or lunchbox, adding the edamame and fruit to the other compartments.', 0),
(16, 'rubix', '2021-06-23 12:26:54', 'Japanese salad with ginger soy dressing', 30, 2, 4, 'Salad', 'Japanese', 'images/articles/dee47537a0a3989871e80af0c5722025.jpg', 'Serve this salad alongside grilled tuna or steak or tuck into it as a superhealthy lunch', '4 baby gem lettuces , halved lengthways\r\n200g frozen shelled edamame (soy) beans, defrosted\r\n4 carrots , cut into long matchsticks\r\n140g radish , thinly sliced\r\n\r\nFor the dressing\r\n\r\n2 tbsp rice wine vinegar\r\n2 tbsp reduced-salt soy sauce\r\n2 tbsp caster sugar\r\n½ small onion , chopped\r\n2 tsp chopped ginger\r\n1 tbsp tomato purée\r\n2 tbsp vegetable oil', 'STEP 1\r\nPlace all the dressing ingredients in a blender or food processor and add 1 tbsp water. Blend until smooth. Arrange the halved lettuce, edamame, carrots and radishes on 4 plates or 1 big platter. When ready to serve, drizzle the dressing over.', 0),
(17, 'rubix', '2021-06-23 12:38:06', 'Chinese chicken noodle soup with peanut sauce', 15, 30, 2, 'Main Course', 'Chinese', 'images/articles/1624432086_Chinese chicken noodle soup with peanut sauce.jpg', 'Cook an exotic yet easy chicken noodle soup and liven it up with a spicy peanut sauce – ideal for busy weekdays. Its low-calorie, with two of your 5-a-day', '1 tbsp sunflower oil\r\n4 skinless boneless chicken thighs\r\n1 garlic clove , crushed\r\n1 thumb-sized piece ginger , grated\r\n500ml chicken stock\r\n1 tsp soy sauce\r\n½ hispi cabbage , finely sliced\r\n150g mushrooms\r\n150g straight to wok noodles (we used udon)\r\nFor the peanut sauce\r\n1 tbsp peanut butter\r\n1 tsp soy sauce\r\n1 tsp honey\r\nsriracha or other chilli sauce (optional), to serve', 'STEP 1\r\nHeat the oil in a saucepan over a medium heat, add the chicken and brown a little, so around 2-3 mins, then add the garlic and ginger and stir to coat the chicken. Fry for a further minute, then pour in the chicken stock and soy, bring to the boil, then reduce to a simmer. Cover with a lid and leave to gently bubble for 25-30 mins until the chicken is tender and pulls apart.\r\n\r\nSTEP 2\r\nMeanwhile, mix the sauce ingredients with a splash of water. When the chicken is ready, lift it out with a slotted spoon and use two forks to shred it on a plate. Add the cabbage, mushrooms and noodles to the pan, turn up the heat, then stir in the chicken, add a dash of sriracha, if using, and ladle into bowls. Top with a drizzle of the peanut sauce and serve.', 0),
(18, 'rubix', '2021-06-23 12:50:12', 'Mexican chicken tortilla soup', 40, 80, 8, 'Appetizer', 'Mexican', 'images/articles/download.jpg', 'A hearty Central American soup with complex flavours and textures. If you can make it the day before serving, the flavours will intensify', '1.2kg whole chicken\r\n5 fat red chillies , 4 left whole but pierced a few times with a sharp knife, 1 sliced, to serve\r\n2 dried ancho chillies\r\n1 garlic bulb , cut in half through the centre horizontally\r\nbunch coriander , stalks and leaves separated\r\n1 cinnamon stick\r\n3 tbsp vegetable oil\r\n2 large onions , chopped\r\n1 tbsp ground cumin\r\n1 tbsp ground coriander\r\n1 tbsp smoked paprika\r\n2 x 400g cans tomatoes\r\n1 tsp sugar\r\n320g can sweetcorn , drained\r\n400g can black beans , drained\r\nzest and juice 2 limes\r\n4 corn tortilla , quartered and cut into strips\r\n2 avocados\r\n200g feta or queso fresco, crumbled, to serve', 'STEP 1\r\nPut the chicken in a large pan with the whole and dried chillies, garlic, coriander stalks and cinnamon, cover with cold water, then set over a medium heat. When the liquid comes to the boil, reduce to a gentle simmer and cover with a lid. Cook for 30 mins, then turn off the heat and leave the chicken in the stock to cool for 20 mins.\r\n\r\nSTEP 2\r\nRemove the chicken, strain the liquid into a large jug (you should have about 800ml) and discard the aromatics. Return the liquid to the pan and simmer until it has reduced to about 600ml, then pour back into the jug.\r\n\r\nSTEP 3\r\nHeat 1 tbsp oil in the pan, add the onion and cook for 8-10 mins until soft and translucent, then stir in the spices, tomatoes and sugar. Add the chicken stock to the pan, season well and simmer with the lid ajar for 30 mins.\r\n\r\nSTEP 4\r\nWhile the soup cooks, remove the skin from the chicken and finely shred the meat. Add to the soup along with the sweetcorn, beans, lime zest and juice to taste (save a little to toss through the avocado), and cook for 5 mins more.\r\n\r\nSTEP 5\r\nHeat the remaining oil in a frying pan and add the tortilla pieces. Fry until golden and crispy, then drain on kitchen paper. Halve and peel the avocado, cut into small chunks and toss through the remaining lime juice. Serve the soup in bowls topped with the crispy tortillas, coriander leaves, sliced chilli, avocado and feta.', 0),
(19, '4nm19cs192', '2021-06-23 12:56:41', 'Mexican bean soup with crispy feta tortillas', 10, 15, 4, 'Main Course', 'Mexican', 'images/articles/Mexican bean soup with crispy feta tortillas.jpg', 'A low-fat, vegetarian midweek meal, this hearty soup with cheesy tortillas makes for a moreish combination.', '1 tbsp vegetable oil\r\n1 onion , chopped\r\n1 heaped tbsp chipotle paste\r\n500g carton passata\r\n500ml vegetable stock\r\n400g can kidney beans , drained and rinsed\r\n400g can black beans , drained and rinsed\r\n200g feta\r\n2 garlic cloves , crushed\r\n4 large or 8 small flour tortillas\r\nsmall pack coriander , roughly chopped, to serve', 'STEP 1\r\nHeat the oil in a large pan and cook the onion over a medium heat for 10 mins to soften. Stir in the chipotle paste, passata, stock and all the beans. Season, bring to the boil, then gently simmer for 5 mins.\r\n\r\nSTEP 2\r\nMeanwhile, in a bowl crumble the feta and mix with the garlic. Divide between the tortillas, spreading over one half of each, then sprinkle over a little pepper. Fold the uncovered side over and press down. Heat a dry frying pan and cook the tortillas on both sides for a couple of mins until the feta has melted and the tortillas are crisp.\r\n\r\nSTEP 3\r\nDivide the soup between bowls, scatter with coriander and serve with the tortillas.', 0),
(20, 'simple', '2021-06-23 13:03:01', 'Monkey bread', 75, 35, 12, 'Dessert', 'American', 'images/articles/Monkey bread.jpg', 'This American, pull-apart sweet treat is sticky, spiced and stuffed with pecans - an indulgent breakfast, brunch or dessert to share', 'For the dough\r\n\r\n200ml semi-skimmed milk\r\n85g unsalted butter\r\n2 large eggs\r\n550g strong white bread flour , plus extra for kneading if doing it by hand\r\n2½ tsp fast-action dried yeast\r\n50g golden caster sugar\r\noil , for greasing\r\n\r\nTo assemble\r\n\r\n125g unsalted butter , plus extra for greasing\r\n1 tbsp ground cinnamon\r\n1 tsp ground ginger\r\n1 tsp ground nutmeg\r\n225g light muscovado sugar\r\n140g pecans , toasted then roughly chopped\r\n\r\nFor the glaze\r\n\r\n100g icing sugar , sifted\r\n½ tsp vanilla extract\r\n1 tbsp semi-skimmed milk\r\npinch of ground cinnamon\r\n2 tbsp unsalted butter , melted', 'STEP 1\r\nStart with the dough. Put the milk and butter into a medium pan and heat gently until the butter melts and the milk is at a simmer. Cool for a few mins, then beat in the eggs with a fork. Mix the dry ingredients in a large bowl with 1½ tsp fine salt, then add the liquid and stir to a sticky dough. Leave for 5 mins, then tip onto a floured worktop and knead for 5-10 mins until smooth and springy. Use a little oil to grease a large bowl, add the dough, turn it in the oil to coat, then cover the bowl with clingfilm. Leave in a warm place for 1 hr or until doubled in size. Knead in a tabletop mixer with a dough hook if you prefer.\r\n\r\nSTEP 2\r\nTo assemble, grease a 25cm bundt pan with butter. Melt the rest of the butter in a pan. In a medium bowl mix the spices and sugar plus a pinch of salt. Spoon 2 tbsp melted butter, 3 tbsp spiced sugar and 4 tbsp pecans into the bottom of the tin.\r\n\r\nSTEP 3\r\nPull the dough into about 65 small pieces and roll into balls. Taking 4 or 5 at a time, dunk the dough balls into the melted butter, let the excess drain off, then tip them into the spiced sugar. Roll to coat, then put haphazardly into the tin. Repeat until theres a full layer of dough in the tin. Scatter with the rest of the chopped nuts, then carry on filling the tin with the coated dough balls. Tip any leftover sugar and butter over the dough. Can be frozen now for up to 1 month. Defrost in the fridge then let prove.\r\n\r\nSTEP 4\r\nCover the pan with oiled clingfilm then leave to rise in a warm place for 1 hr, or until risen and the dough no longer springs back when you poke it.\r\n\r\nSTEP 5\r\nHeat the oven to 180C/160C fan/gas 4. Bake the monkey bread for 35 mins, or until well risen and golden. Let the pan cool for 5 mins, then give it a sharp rap on the counter. Leave in the tin until just warm.\r\n\r\nSTEP 6\r\nWhisk all of the ingredients together to make the glaze. It will thicken as the melted butter cools. Turn the monkey bread onto a serving plate, then drizzle with the glaze. Let it set, if you can bear the wait.', 0);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `blogpost`
--
ALTER TABLE `blogpost`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `blogpost`
--
ALTER TABLE `blogpost`
  MODIFY `id` int(5) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
